[params]

[params.author]
  name = "Aimee M. Van Tatenhove, Ph.D."
  image = "portrait-color.jpg"
  headline = "Quantitiative Ecologist"
  bio = ""
  links = [
  #   { email = "mailto:hello@your_domain.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { bluesky = "..." },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/s0avant" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
    { google-scholar = "https://scholar.google.com/citations?hl=en&user=-Uax-WsAAAAJ" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://www.instagram.com/aimeevantatenhove/" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { kofi = "https://ko-fi.com/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://www.linkedin.com/in/aimee-van-tatenhove-319b0bb4/" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { mendeley = "https://www.mendeley.com/" },
  #   { microsoft = "https://www.microsoft.com/" },
    { orcid = "https://orcid.org/0000-0003-2483-1055" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
    { researchgate = "https://www.researchgate.net/profile/Aimee-Van-Tatenhove" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { threads = "https://threads.net/@username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { x-twitter = "https://twitter.com/username" },
    { youtube = "https://www.youtube.com/@aimeevantatenhove7894" },
  #   { xing = "https://xing.com/profile/username" },
  ]
