baseURL = "https://www.avantatenhove.com/"
languageCode = "en-us"
title = "avantatenhove"
theme = "air"

[params]
  author = { name = "Aimee M. Van Tatenhove PhD", siteUrl = "https://www.avantatenhove.com" }
  gmaps_url = ""
  [params.footer]
    copyright = "© 2018–{year} Aimee M. Van Tatenhove, Ph.D."
    
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[services.googleAnalytics]
  id = "" #G-MKFPZMY2YP

[[menu.main]]
  name = "About"
  pageRef = "/"
  weight = 10

[[menu.main]]
  name = "CV"
  pageRef = "/cv"
  weight = 20

[[menu.main]]
  name = "Resources"
  pageRef = "/resources"
  weight = 30

[[menu.main]]
  name = "Media"
  pageRef = "/media"
  weight = 40

[[menu.main]]
  name = "Contact"
  pageRef = "/contact"
  weight = 50

[markup.goldmark.parser.attribute]
  block = true

[markup.goldmark.renderer]
  unsafe = true

[privacy]
  [privacy.googleAnalytics]
    disable = true
    respectDoNotTrack = true

  [privacy.youTube]
    disable = false
    privacyEnhanced = true